In [68]:
print(5+4)

9


In [69]:
x = [1,2,3,4,"Mame"]

for i in x: 
    print(i)

1
2
3
4
Mame


In [70]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [71]:
for i in range(20,0, -1):
    print(i)

20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [72]:
for i in range(1,20):
    c = i%5
    if(c != 0):
        print(i)
     
        
        

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


In [74]:
x = int(input("How many candy do you want?"))
avaliable_candies = 5

i = 1

while i<= x:
    if(i > avaliable_candies):
        print("Out of stock")
        break
    print("Candy")
    i+=1
    
    
print('Bye')

How many candy do you want?45
Candy
Candy
Candy
Candy
Candy
Out of stock
Bye


In [75]:
for i in range(1,10):
    three = i%3
    five = i%5
    if(three == 0 or five == 0):
        print("divisibe by 3 or 5")
        continue
    else:
        print(i)
        
    
    
        
    
        
    
    
    

        
    

1
2
divisibe by 3 or 5
4
divisibe by 3 or 5
divisibe by 3 or 5
7
8
divisibe by 3 or 5


In [76]:
for i in range(1,10):
    if(i%2!= 0):
        #i dont have anything to say
        pass
    else:
        print(i)

        
print('Bye')
#continue--- will skip the value and continue the iteration
#break---- will come out of the loop. Break out of the loop 
#pass ---to keep a function or condition there while not using it
        

2
4
6
8
Bye


In [77]:
for i in range(1,5):
    for j in range(1,5):
        if j <= i :
            print("#", end=" ")
    print(" ")

#  
# #  
# # #  
# # # #  


In [14]:
for i in range(1,5):
    for j in range(1,5):
        if j >= i:
            print("#", end=" ")
    print(" ")

# # # #  
# # #  
# #  
#  


In [18]:
nums = [ 12,15,18,25, 26]


for i in nums:
    if i%5 ==  0:
        print(i)
        break
    

15


In [19]:
nums = [ 12,13,18,24, 26]


for i in nums:
    if i%5 ==  0:
        print(i)
        break
        
else: 
    print("Not found")
    

Not found


In [41]:
num = 10
for i in range(2,num):
    if num % i == 0:
        print(i)
        print(num%i)
        print("Not prime")
        break
else: 
    print("Prime")

2
0
Not prime


In [50]:
import array as arr

vals = arr.array("i", [-4,5,6,2])
print(vals.buffer_info())
vals.reverse()
vals[0]

(2189049587872, 4)


2

In [53]:
import array as arr

vals = arr.array("u", ["j","s","6","2"])
print(vals.buffer_info())
vals.reverse()
vals[0]

(2189049588032, 4)


'2'

In [58]:
all = arr.array("i", [])

n = int(input("Enter the length of the array?"))

for i in range(n):
    num = int(input("Enter your value: "))
    all.append(num)
    
print(all)

val = int(input("enter the value you want to check: "))
k = 0
for i in all:
    if i == val:
        print(k)
        break
    k+=1

Enter the length of the array?7
Enter your value: 3
Enter your value: 4
Enter your value: 5
Enter your value: 6
Enter your value: 7
Enter your value: 8
Enter your value: 9
array('i', [3, 4, 5, 6, 7, 8, 9])
enter the value you want to check: 9
6


In [2]:
from numpy import *

arr = array([1,2,3,4.0])

print(arr)
arr.dtype

[1. 2. 3. 4.]


dtype('float64')

In [3]:
arr = linspace(119,189,41) 
arr

array([119.  , 120.75, 122.5 , 124.25, 126.  , 127.75, 129.5 , 131.25,
       133.  , 134.75, 136.5 , 138.25, 140.  , 141.75, 143.5 , 145.25,
       147.  , 148.75, 150.5 , 152.25, 154.  , 155.75, 157.5 , 159.25,
       161.  , 162.75, 164.5 , 166.25, 168.  , 169.75, 171.5 , 173.25,
       175.  , 176.75, 178.5 , 180.25, 182.  , 183.75, 185.5 , 187.25,
       189.  ])

In [4]:
arr = arange(1,30,2)

arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [5]:
arr = logspace(1,10,5)

arr

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [6]:
arr = zeros(5)
arr2 = ones(5,int)
print(arr);
arr2

[0. 0. 0. 0. 0.]


array([1, 1, 1, 1, 1])

In [7]:
arr = array([1,2,3,4,5])
#how to add all element in an array without for loop
arr = arr+5
arr

array([ 6,  7,  8,  9, 10])

In [8]:
arr2 = array([1,3,4,5,6])

arr3 = arr + arr2

arr3

array([ 7, 10, 12, 14, 16])

In [9]:
print(sqrt(arr3))

[2.64575131 3.16227766 3.46410162 3.74165739 4.        ]


In [10]:
print(sort(arr))

[ 6  7  8  9 10]


In [11]:
arr1 = array([
    
    [1,2,3],
    [2,3,4]
])

arr1.ndim

2

In [12]:
arr1.shape

(2, 3)

In [14]:
arr1.size

6

In [16]:
arr1.flatten
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
arr2 = arr1.flatten() 
print(arr2)

[1 2 3 2 3 4]


In [23]:
arr3 = arr2.reshape(2,3)
arr3

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
m =matrix(arr3)
m

matrix([[1, 2, 3],
        [2, 3, 4]])

In [25]:
m1 = matrix('1 2 3; 4 5 6; 7 8 9')
m2 = matrix('1 2 3; 4 5 6; 7 8 9')
m3 = m1+ m2
m3




matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [26]:
m3 = m1 * m2
m3

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [27]:
def greet():
    print("hello")
    
greet()

hello


In [28]:
def add(a,b):
    print(a+b)
    
add(4,5)

9


In [30]:
def addi(a,b):
    c = a+b
    return c


addi(2,4)

6

In [31]:
def add_sub(x,y):
    a = x+y
    b = x-y
    return a,b

add_sub(4,2)
    

(6, 2)

In [32]:
def okay(x):
    x= 8
    print(x)
    
okay(3)
    

8


In [34]:
   #keywords
def person(name, age):
    print(name)
    print(age)
      
person(age=56, name="Dami")


Dami
56


In [35]:
   #default
def person(name, age=4):
    print(name)
    print(age)
      
person("Dami")


Dami
4


In [46]:
   #multiple values, single data
def person(a,*b):
    
    total = a
    for i in b:
        total = total + i
    return total
person(2,2,3,5,7)


19

In [52]:
#keyworded variable length arguments

#multiple data


def person(name, **data):
    print(name)
    for i,j in data.items():
            print(i,j)
    

person("Dami", age=16,classe="ss2")




Dami
age 16
classe ss2


In [53]:
#global keywords

a= 10 # a global variable

def something():
    a = 15 # local variable
    
    print("Local: ", a)
    
print("Global: ", a)

something()

Global:  10
Local:  15


In [56]:
#global keywords

a= 10 # a global variable

def something():
    global a #to make the variable global
    a = 15 # local variable
    
    print("Local: ", a)
    
something()
    
print("Global: ", a)


Local:  15
Global:  15


In [63]:
list = [1,2,3,4,5,6,7,8,9,10,11]

def count(a):
    
    odd = []
    even = []
    for i in a:
        if i%2==0:
            even.append(i)
        else:
            odd.append(i)
    print("No of odd: ", len(odd))
    print("No of even: ",len(even))
    

count(list)

No of odd:  6
No of even:  5


In [93]:


def count():
    list_no = int(input("How many numbers are you willing to check?"))
    
    list = []
    for i in range(list_no):
        b = int(input("Enter a value: "))
        list.append(b)
    #print(list)
    odd = []
    even = []
    for i in list:
        if i%2==0:
            even.append(i)
        else:
            odd.append(i)
    return(len(odd), len(even))
   


x,y = count()
print("Even: {}; Odd: {}".format(y,x))

How many numbers are you willing to check?1
Enter a value: 2
Even: 1; Odd: 0


In [100]:
def factorial():
    num = int(input('Enter the number you want:'))
    list = []
    for i in range(1,num+1):
        list.append(i)
    multiply=1   
    for i in list:
        multiply = multiply * i8
    print(multiply)    
        

factorial()

Enter the number you want:3
6


In [102]:
def factorial():
    num = int(input("enter the number: "))
    
    f = 1
    for i in range(1,num+1):
        f = f*i
    print(f)
    
factorial()

enter the number: 4
24


In [104]:
#recursion
import sys 
sys.setrecursionlimit(2000)
print(sys.getrecursionlimit())


2000


In [105]:
#anonymous functions

f= lambda a: a*a
result = f(5)
print(result)

25


In [106]:
#anonymous functions

f= lambda a,b: a+b
result = f(5,6)
print(result)

11


In [2]:
nums = [1,2,3,4,4,5,6,7]
def isEven(a):
    return a%2==0
evens= list(filter(isEven, nums))
print(evens)


#or using anonymous functions

evens = list(filter(lambda a: a%2==0, nums))
print(evens)

[2, 4, 4, 6]
[2, 4, 4, 6]


In [3]:
square = list(map(lambda a: a*a, evens))
print(square)

[4, 16, 16, 36]


In [6]:
#reduce
from functools import reduce
total= reduce(lambda a,b:a+b, square)
print(total)

72


In [13]:
#decorators: add extra features to existing functions or change the behaviour of a parent fuction by adding a new feature


def div(a,b):
    print(a/b)
    
def smart_div(func):
    def inner(a,b):
        if a< b:
            a,b=b,a
        return func(a,b)
    return inner

div = smart_div(div)
div(5,10)


2.0


In [14]:
print(__name__)

__main__


In [15]:
#object oriented programming: Class

class Computer:
    def config(self):

        print("i5", '16gb', '1tb')

com1 = Computer().config()

#or
com1 = Computer()
Computer.config(com1)

#or
com1.config()
        


i5 16gb 1tb
i5 16gb 1tb
i5 16gb 1tb


In [19]:
class Car:
    wheels = 4 #Class variables or Static variables:  common to all objects
    def __init__(self):
        self.mil = 10   # instance variables: they are within the init method
        self.com ="BMW"

        
c1 = Car()
c2 = Car()

c1.mil=20
Car.wheels= 5
print(c1.com, c1.mil, c1.wheels)
c2.com, c2.mil, c2.wheels

BMW 20 5


('BMW', 10, 5)

In [1]:
class Student:
    school = "Fgc,Lagos"
    
    def __init__(self, m1,m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    def average(self):#This is an instance method, because we passed SELF
        return (self.m1 + self.m2 + self.m3)/3
    
    def set_m1(self, value):
        self.m1 = value
    @classmethod    #decorators
    def getSchool(cls): #Class methods
        return cls.school
    
    @staticmethod
    def info(): #Static method
        print('This a student class')
    
    
        
        
        

s1 = Student(23,4,5)
s2 = Student(3,6,7)
s2.set_m1(34)

print(Student.getSchool())
Student.info()

s1.average(),s2.average()

Fgc,Lagos
This a student class


(10.666666666666666, 15.666666666666666)

In [11]:
#Inheritance
class A:
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")

        
class B(A):# B is inheriting the features of class A
    def feature3(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")

class C(B): #C is inheriting from B and A
    def feature5(self):
        print("Feature 5 is working")
    
class D: 
    def feature6(self):
        print("This is feature 6")
class E(A,D):#Multiple inheritance
    def feature7(self):
        print("This is feature 7")
        
a1 = A()

b1 = B()

c1 = C()


e1 = E()

e1.feature1()
b1.feature1()#Single level inheritance

a1.feature1()

c1.feature2()#Multilevel inheritance


Feature 1 working
Feature 1 working
Feature 1 working
Feature 2 working


In [15]:
#Constructor in Inheritance

class A:
    def __init__(self):
        print("Init A")
    def feature1(self):
        print("Feature 1 working")
    def feature2(self):
        print("Feature 2 working")

        
class B(A):# B is inheriting the features of class A
    def __init__(self):
        super().__init__()# to call the init method of super class i.e A
        print("Init B")
    def feature3(self):
        print("Feature 3 working")
    def feature4(self):
        print("Feature 4 working")

b1 = B()#an instance of a class also inherit constructor from parent class





Init A
Init B


In [22]:
class A:
    def __init__(self):
        print("Init A")
    def feature1(self):
        print("Feature 1-A working")
    def feature2(self):
        print("Feature 2 working")

        
class B:
    def __init__(self):
       print("init b")
    def feature1(self):
        print("Feature 1_B working")
    def feature4(self):
        print("Feature 4 working")

class C(A,B):
    def __init__(self):
        super().__init__()#call the constructor of left class A
        print("Init C")
        
    def  feat(self):
        super().feature4()# Inheritance with methods
        
  

        
c1 = C()
c1.feature1()
c1.feat()

Init A
Init C
Feature 1-A working
Feature 4 working


In [23]:
#Polymorphism: one thing in many form

#Duck Typing

class Pycharm:
    def execute(self):
        print("Execute")
        print("program")

class Vscode:
    def execute(self):
        print("the best")
        print("also the best")
        
class Laptop:
    def code(self, editor):
        editor.execute()
        
lap1 = Laptop()

lap1.code(Vscode())




the best
also the best


In [32]:
#operator overloading

print(int.__add__(6,5))

class Student:
    def __init__(self, m1,m2):
        self.m1 =m1
        self.m2 =m2
        
    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2+ other.m2
        
        s3 = Student(m1,m2)
        
        return s3
    
    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        
        if r1 > r2:
            return True
        else:
            return False
        
        
s1 = Student(50,60)
s2 = Student(45,67)
s3 = s1+s2
print(s3.m1,s3.m2)

if s1 > s2:
    print("s1 wins")
else: 
    print("s2 wins")

11
95 127
s2 wins


In [34]:
#method overloading: 
class Student:
    def __init__(self, m1,m2):
        self.m1 =m1
        self.m2 =m2
        
        
    def sum(self,a,b):
        s = a+ b
        return s
    
s1 = Student(34,56)

s1.sum(2,4)



6

In [37]:
#method overriding

class A:
    def show(self):
        print("in a show")
    
class B(A):
    def show(self):
        print("b show")


a1 = B()
a1.show()

b show


In [40]:
#generators

def topten():
    
    yield 5
    
    
    
    

    
values = topten()


print(values)

<generator object topten at 0x000001AB08430740>


In [44]:
#exception handling

a = 5
b = 0
try:
    print(a/b)# becuse there is an error here nd we want command to execute the next statement
except ZeroDivisionError as e:
    print("You cannot divide a number by zero", e)
except ValueError as e:
    print("Invalid input", e)
    
except Exception as e:
    print("something went wrong")

finally:
    print("I will work regardless")
    
print("bye")



You cannot divide a number by zero division by zero
bye


In [69]:
#multithreading: 

# from threading import *
# from time import sleep

# class Hello(Thread):
#     def run(self):
# #         for i in  range(0):
# #             #print("Hello")
# #             sleep(1)
    
    
    
# class Hi(Thread):
#     def run(self):
# #         for i in range(0):
# #             #print("Hi")
# #             sleep(1)
            
# t1 = Hello()
# t2 = Hi()

# # t1.start()
# # sleep(0.2)
# # t2.start()
# # t1.join()
# # t2.join()
# # print('Bye')

Hi
Hello
Hello
Hi
Hi
Hello
Hello
Hi
Hi
Hello
Hello
Hi
Hi
Hello
Hello
Hi
Hi
Hello
Hello
Hi
Hi
Hello
Hello
Hi


In [24]:
f = open('sample.txt', 'r')
#f.read()

#print(f.readline(4), end="")


In [25]:
f1 = open('abc.txt', 'w')
f1.write("Something good is happening soon")

32

In [26]:
f1 = open('abc.txt', 'a')

f1.write("Something extra")

15

In [27]:
for data in f:
    f1.write(data)

In [39]:
#linear search

arr = [3,4,5,6,7,8]


def search(list, n):
    i = 0
    for a in list:
        
        if a==n:
            globals() ['pos'] = i

            return True
        i+=1
    else:
        return False

if search(arr,4):
    print("Found", pos+1)
else:
    print("Not found")

Found 2


In [ ]:
#Binary search

#the array is sorted first

In [2]:
import mysql.connector
mydb =mysql.connector.connect(host='localhost', user='root', passwd='1234')

In [6]:
#zip
names = ['navin', 'dami', 'shola']
other = ['class', 'school', 'tops']

zipped = list(zip(names, other))

zipped

for a,b in zipped:
    print(a,b)
    




navin class
dami school
shola tops


In [ ]:
    import flask as Flask
    